# Generated by Django 6.0.7 on 2026-08-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortalDatasetIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_id', models.CharField(max_length=255, unique=True)),
                ('datatype', models.CharField(db_index=True, max_length=64)),
                ('repository', models.CharField(default='spp-unit-bundles', max_length=128)),
                ('unit', models.CharField(blank=True, max_length=255)),
                ('bucket', models.CharField(max_length=255)),
                ('manifest_key', models.TextField()),
                ('dataset_prefix', models.TextField()),
                ('title', models.TextField()),
                ('year', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('files', models.JSONField(default=list)),
                ('ingestion_status', models.CharField(choices=[('in_sync', 'In sync'), ('invalid', 'Invalid'), ('out_of_sync', 'Out of sync'), ('hidden', 'Hidden'), ('withdrawn', 'Withdrawn')], db_index=True, default='invalid', max_length=32)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('public', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('withdrawn', models.BooleanField(default=False)),
                ('indexed_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['datatype', 'ingestion_status'], name='portal_data_datatyp_b78217_idx'), models.Index(fields=['repository'], name='portal_data_reposit_cfd210_idx'), models.Index(fields=['unit'], name='portal_data_unit_29318e_idx'), models.Index(fields=['year'], name='portal_data_year_817b3a_idx')],
            },
        ),
    ]
