services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
      target: dev
    entrypoint: python manage.py runserver 0.0.0.0:8000
    container_name: pathogens_portal_web
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
        restart: true
    volumes:
      - type: bind
        source: ./
        target: /app

  db:
    image: postgres:17
    container_name: pathogens_portal_db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - type: volume
        source: postgres_db
        target: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready --username=${POSTGRES_USER} --dbname=${POSTGRES_DB}
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  postgres_db:
