# Generated by Django 6.0.7 on 2026-09-03 15:08

import cms.blocks.publications
import django.core.validators
import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.routable_page.models
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('wagtailcore', '0098_apitoken'),
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.WAGTAIL_PAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableDataPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('content', wagtail.fields.StreamField([('text', 0), ('alert', 3), ('available_data', 4)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h4', 'h5', 'bold', 'italic', 'link'], 'help_text': 'Alert body. Rich text only: headings H4–H5, bold, italic, and links.'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], 'help_text': 'Controls the visual style (colour) of the alert on the public site.'}), 3: ('wagtail.blocks.StructBlock', [[('message', 1), ('alert_type', 2)]], {}), 4: ('wagtail.blocks.static_block.StaticBlock', (), {'admin_text': 'Displays EBI dataset counts by category, loaded via HTMX. NOTE: This requires the page to be published until then, previewing it will show an error instead of the counts.', 'template': 'cms/pages/available_data/partials/available_data_section.html'})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BasicPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('show_toc', models.BooleanField(blank=True, default=False, verbose_name='Show TOC')),
                ('content', wagtail.fields.StreamField([('text', 0), ('alert', 3), ('data_table', 12), ('collapsible', 16), ('matomo_opt_out', 17)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Main body copy. Use headings for structure; images optional.', 'verbose_name': 'Text (rich)'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h4', 'h5', 'bold', 'italic', 'link'], 'help_text': 'Alert body. Rich text only: headings H4–H5, bold, italic, and links.'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], 'help_text': 'Controls the visual style (colour) of the alert on the public site.'}), 3: ('wagtail.blocks.StructBlock', [[('message', 1), ('alert_type', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Unique identifier for this table on the page (letters, numbers, hyphens). Defaults to a slugified version of the table caption.', 'max_length': 60, 'required': False, 'validators': [django.core.validators.RegexValidator('^[a-zA-Z0-9-]*$', 'Only letters, numbers, and hyphens.')]}), 5: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Show search, pagination, and per-page controls.', 'required': False}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('10', '10'), ('25', '25'), ('50', '50')], 'help_text': 'Number of rows per page when controls are visible (display all entries if controls are not shown).', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {}), 8: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 9: ('wagtail.blocks.FloatBlock', (), {}), 10: ('wagtail.blocks.IntegerBlock', (), {}), 11: ('wagtail.contrib.typed_table_block.blocks.TypedTableBlock', [[('text', 7), ('rich_text', 8), ('numeric', 9), ('integer', 10)]], {}), 12: ('wagtail.blocks.StructBlock', [[('table_id', 4), ('show_controls', 5), ('per_page', 6), ('table', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'Title shown in the always-visible summary line.', 'max_length': 255, 'required': True}), 14: ('wagtail.blocks.RichTextBlock', (), {}), 15: ('wagtail.blocks.StreamBlock', [[('text', 14), ('data_table', 12)]], {'help_text': 'Inner content revealed when the section is opened.', 'min_num': 1}), 16: ('wagtail.blocks.StructBlock', [[('label', 13), ('body', 15)]], {}), 17: ('wagtail.blocks.static_block.StaticBlock', (), {'admin_text': 'Displays the Matomo analytics opt-out widget.', 'template': 'cms/components/matomo_opt_out.html'})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CataloguePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('filter_label', models.CharField(max_length=100)),
                ('content', wagtail.fields.StreamField([('text', 0), ('alert', 3), ('card_grid', 12)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Rich text content. Supports headings, links, etc. for formatting.', 'verbose_name': 'Text (rich)'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h4', 'h5', 'bold', 'italic', 'link'], 'help_text': 'Alert body. Rich text only: headings H4–H5, bold, italic, and links.'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], 'help_text': 'Controls the visual style (colour) of the alert on the public site.'}), 3: ('wagtail.blocks.StructBlock', [[('message', 1), ('alert_type', 2)]], {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Image shown at the top of the card (required).', 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Card heading (max 120 characters).', 'max_length': 120, 'required': True}), 6: ('wagtail.blocks.TextBlock', (), {'help_text': 'Short supporting text under the title (max 300 characters).', 'max_length': 300, 'required': True}), 7: ('wagtail.blocks.URLBlock', (), {'help_text': 'Full URL (https://…). Opens in a new browser tab.', 'required': True}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Comma-separated types, used in filtering and labeling (Max 120 characters).', 'max_length': 120, 'required': True}), 9: ('wagtail.blocks.TextBlock', (), {'help_text': 'Optional comma-separated keywords for filtering (Max 300 characters).', 'max_length': 300, 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('image', 4), ('title', 5), ('description', 6), ('url', 7), ('type', 8), ('keywords', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {'collapsed': True, 'help_text': 'Add at least one card. Each card links to an external URL and includes catalogue type and keywords for filtering.', 'label': 'Catalogue cards', 'min_num': 1}), 12: ('wagtail.blocks.StructBlock', [[('cards', 11)]], {'help_text': 'Catalogue items added here will be displayed in a grid layout. The items are rendered as cards and ordered alphabetically.'})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('content', wagtail.fields.StreamField([('text', 0), ('alert', 3), ('contact_form', 4)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h4', 'h5', 'bold', 'italic', 'link'], 'help_text': 'Alert body. Rich text only: headings H4–H5, bold, italic, and links.'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], 'help_text': 'Controls the visual style (colour) of the alert on the public site.'}), 3: ('wagtail.blocks.StructBlock', [[('message', 1), ('alert_type', 2)]], {}), 4: ('wagtail.blocks.static_block.StaticBlock', (), {'admin_text': 'Contact form rendered from a template.', 'template': 'cms/pages/contact/partials/contact_form.html'})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='DashboardIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('content', wagtail.fields.StreamField([('text', 0), ('alert', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h4', 'h5', 'bold', 'italic', 'link'], 'help_text': 'Alert body. Rich text only: headings H4–H5, bold, italic, and links.'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], 'help_text': 'Controls the visual style (colour) of the alert on the public site.'}), 3: ('wagtail.blocks.StructBlock', [[('message', 1), ('alert_type', 2)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='DashboardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('show_toc', models.BooleanField(blank=True, default=False, verbose_name='Show TOC')),
                ('description', models.CharField(max_length=255)),
                ('data_status', models.CharField(choices=[('active', 'Active'), ('historic', 'Historic')], max_length=50)),
                ('keywords', models.TextField(blank=True)),
                ('ebi_data_type', models.CharField(blank=True, max_length=255, verbose_name='EBI data type')),
                ('ebi_data_source', models.CharField(blank=True, max_length=255, verbose_name='EBI data source')),
                ('content', wagtail.fields.StreamField([('text', 0), ('alert', 3), ('collapsible', 15), ('data_table', 13), ('last_updated', 18), ('plotly_figure', 25), ('static_figure', 30)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h4', 'h5', 'bold', 'italic', 'link'], 'help_text': 'Alert body. Rich text only: headings H4–H5, bold, italic, and links.'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], 'help_text': 'Controls the visual style (colour) of the alert on the public site.'}), 3: ('wagtail.blocks.StructBlock', [[('message', 1), ('alert_type', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Title shown in the always-visible summary line.', 'max_length': 255, 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Unique identifier for this table on the page (letters, numbers, hyphens). Defaults to a slugified version of the table caption.', 'max_length': 60, 'required': False, 'validators': [django.core.validators.RegexValidator('^[a-zA-Z0-9-]*$', 'Only letters, numbers, and hyphens.')]}), 6: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Show search, pagination, and per-page controls.', 'required': False}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('10', '10'), ('25', '25'), ('50', '50')], 'help_text': 'Number of rows per page when controls are visible (display all entries if controls are not shown).', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {}), 9: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 10: ('wagtail.blocks.FloatBlock', (), {}), 11: ('wagtail.blocks.IntegerBlock', (), {}), 12: ('wagtail.contrib.typed_table_block.blocks.TypedTableBlock', [[('text', 8), ('rich_text', 9), ('numeric', 10), ('integer', 11)]], {}), 13: ('wagtail.blocks.StructBlock', [[('table_id', 5), ('show_controls', 6), ('per_page', 7), ('table', 12)]], {}), 14: ('wagtail.blocks.StreamBlock', [[('text', 0), ('data_table', 13)]], {'help_text': 'Inner content revealed when the section is opened.', 'min_num': 1}), 15: ('wagtail.blocks.StructBlock', [[('label', 4), ('body', 14)]], {}), 16: ('wagtail.blocks.CharBlock', (), {'default': 'Last updated', 'help_text': 'Label shown before the date (e.g. "All data last updated").', 'required': False}), 17: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional text after the date (e.g. "(no longer updating)").', 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('label', 16), ('suffix', 17)]], {}), 19: ('wagtail.blocks.CharBlock', (), {'help_text': 'Key matching a figure in the DashboardData JSON.', 'required': True}), 20: ('wagtail.blocks.CharBlock', (), {'help_text': 'Accessibility description (aria-label) for the chart.', 'required': True}), 21: ('wagtail.blocks.IntegerBlock', (), {'default': 500, 'help_text': 'Chart height in pixels.', 'required': True}), 22: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional visible caption below the chart (separate from alt text).', 'required': False}), 23: ('wagtail.blocks.URLBlock', (), {'help_text': 'Link to the viz script in this repo on GitHub.', 'required': False}), 24: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Show a link to download the underlying data file.', 'required': False}), 25: ('wagtail.blocks.StructBlock', [[('figure_id', 19), ('alt_text', 20), ('height', 21), ('caption', 22), ('script_github_url', 23), ('show_data_download', 24)]], {}), 26: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Upload an image, or leave empty and provide an external URL below.', 'required': False}), 27: ('wagtail.blocks.URLBlock', (), {'help_text': 'External image URL (e.g., Github, blobserver SVG). Used when no image is uploaded.', 'required': False}), 28: ('wagtail.blocks.CharBlock', (), {'help_text': 'Accessibility description (alt attribute) for the image.', 'required': True}), 29: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional visible caption below the figure (separate from alt text).', 'required': False}), 30: ('wagtail.blocks.StructBlock', [[('image', 26), ('image_url', 27), ('alt_text', 28), ('caption', 29)]], {})})),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HighlightsAndEditorialsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('content', wagtail.fields.StreamField([('text', 0), ('alert', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h4', 'h5', 'bold', 'italic', 'link'], 'help_text': 'Alert body. Rich text only: headings H4–H5, bold, italic, and links.'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], 'help_text': 'Controls the visual style (colour) of the alert on the public site.'}), 3: ('wagtail.blocks.StructBlock', [[('message', 1), ('alert_type', 2)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NavigationMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Navigation menu',
                'verbose_name_plural': 'Navigation menu',
            },
        ),
        migrations.CreateModel(
            name='NewsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('content', wagtail.fields.StreamField([('text', 0), ('alert', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h4', 'h5', 'bold', 'italic', 'link'], 'help_text': 'Alert body. Rich text only: headings H4–H5, bold, italic, and links.'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], 'help_text': 'Controls the visual style (colour) of the alert on the public site.'}), 3: ('wagtail.blocks.StructBlock', [[('message', 1), ('alert_type', 2)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='OutbreaksIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('content', wagtail.fields.StreamField([('text', 0), ('alert', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h4', 'h5', 'bold', 'italic', 'link'], 'help_text': 'Alert body. Rich text only: headings H4–H5, bold, italic, and links.'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], 'help_text': 'Controls the visual style (colour) of the alert on the public site.'}), 3: ('wagtail.blocks.StructBlock', [[('message', 1), ('alert_type', 2)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PlpCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('group_label', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'PLP category',
                'verbose_name_plural': 'PLP categories',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PlpIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('content', wagtail.fields.StreamField([('text', 0), ('alert', 3), ('collapsible', 15)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h4', 'h5', 'bold', 'italic', 'link'], 'help_text': 'Alert body. Rich text only: headings H4–H5, bold, italic, and links.'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], 'help_text': 'Controls the visual style (colour) of the alert on the public site.'}), 3: ('wagtail.blocks.StructBlock', [[('message', 1), ('alert_type', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Title shown in the always-visible summary line.', 'max_length': 255, 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Unique identifier for this table on the page (letters, numbers, hyphens). Defaults to a slugified version of the table caption.', 'max_length': 60, 'required': False, 'validators': [django.core.validators.RegexValidator('^[a-zA-Z0-9-]*$', 'Only letters, numbers, and hyphens.')]}), 6: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Show search, pagination, and per-page controls.', 'required': False}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('10', '10'), ('25', '25'), ('50', '50')], 'help_text': 'Number of rows per page when controls are visible (display all entries if controls are not shown).', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {}), 9: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 10: ('wagtail.blocks.FloatBlock', (), {}), 11: ('wagtail.blocks.IntegerBlock', (), {}), 12: ('wagtail.contrib.typed_table_block.blocks.TypedTableBlock', [[('text', 8), ('rich_text', 9), ('numeric', 10), ('integer', 11)]], {}), 13: ('wagtail.blocks.StructBlock', [[('table_id', 5), ('show_controls', 6), ('per_page', 7), ('table', 12)]], {}), 14: ('wagtail.blocks.StreamBlock', [[('text', 0), ('data_table', 13)]], {'help_text': 'Inner content revealed when the section is opened.', 'min_num': 1}), 15: ('wagtail.blocks.StructBlock', [[('label', 4), ('body', 14)]], {})})),
            ],
            options={
                'verbose_name': 'PLP program page',
                'verbose_name_plural': 'PLP program pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PortalDataPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('datatype', models.CharField(choices=[('metabolomics', 'Metabolomics')], default='metabolomics', max_length=64)),
                ('default_page_size', models.PositiveIntegerField(default=25)),
                ('content', wagtail.fields.StreamField([('text', 0), ('alert', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h4', 'h5', 'bold', 'italic', 'link'], 'help_text': 'Alert body. Rich text only: headings H4–H5, bold, italic, and links.'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], 'help_text': 'Controls the visual style (colour) of the alert on the public site.'}), 3: ('wagtail.blocks.StructBlock', [[('message', 1), ('alert_type', 2)]], {})})),
            ],
            options={
                'verbose_name': 'Portal data page',
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='PublicationsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('content', wagtail.fields.StreamField([('text', 0), ('alert', 3), ('publications', 9)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h4', 'h5', 'bold', 'italic', 'link'], 'help_text': 'Alert body. Rich text only: headings H4–H5, bold, italic, and links.'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], 'help_text': 'Controls the visual style (colour) of the alert on the public site.'}), 3: ('wagtail.blocks.StructBlock', [[('message', 1), ('alert_type', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Pathogen name shown in the filter sidebar.', 'max_length': 255}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'validators': [cms.blocks.publications.validate_no_quotes]}), 6: ('wagtail.blocks.ListBlock', (5,), {'help_text': "One or more search terms to match against the publication's title or abstract. The query will be constructed as an 'OR' search across all terms. Use multiple terms if the pathogen has multiple names or abbreviations. Don't use quotes in the search terms.", 'min_num': 1}), 7: ('wagtail.blocks.StructBlock', [[('name', 4), ('search_terms', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {'help_text': 'One entry per pathogen to filter on. Displayed alphabetically by name.', 'min_num': 1}), 9: ('wagtail.blocks.StructBlock', [[('pathogens', 8)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SiteAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', wagtail.fields.RichTextField()),
                ('announcement_type', models.CharField(choices=[('maintenance', 'Maintenance'), ('survey', 'Survey')], max_length=20)),
                ('is_enabled', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(blank=True, db_index=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'Site announcement',
                'verbose_name_plural': 'Site announcements',
                'ordering': ['sort_order', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='SLUDashboardSubPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('inherit_notice', models.BooleanField(blank=True, default=True)),
                ('include_in_navigation', models.BooleanField(blank=True, default=True)),
                ('navigation_order', models.PositiveIntegerField(blank=True, default=1)),
                ('show_toc', models.BooleanField(blank=True, default=False, verbose_name='Show TOC')),
                ('slu_content', wagtail.fields.StreamField([('text', 0), ('alert', 3), ('collapsible', 15), ('last_updated', 18), ('plotly_figure', 25), ('site_info', 26), ('virus_quantitative_plot', 27)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h4', 'h5', 'bold', 'italic', 'link'], 'help_text': 'Alert body. Rich text only: headings H4–H5, bold, italic, and links.'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], 'help_text': 'Controls the visual style (colour) of the alert on the public site.'}), 3: ('wagtail.blocks.StructBlock', [[('message', 1), ('alert_type', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Title shown in the always-visible summary line.', 'max_length': 255, 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Unique identifier for this table on the page (letters, numbers, hyphens). Defaults to a slugified version of the table caption.', 'max_length': 60, 'required': False, 'validators': [django.core.validators.RegexValidator('^[a-zA-Z0-9-]*$', 'Only letters, numbers, and hyphens.')]}), 6: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Show search, pagination, and per-page controls.', 'required': False}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('10', '10'), ('25', '25'), ('50', '50')], 'help_text': 'Number of rows per page when controls are visible (display all entries if controls are not shown).', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {}), 9: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 10: ('wagtail.blocks.FloatBlock', (), {}), 11: ('wagtail.blocks.IntegerBlock', (), {}), 12: ('wagtail.contrib.typed_table_block.blocks.TypedTableBlock', [[('text', 8), ('rich_text', 9), ('numeric', 10), ('integer', 11)]], {}), 13: ('wagtail.blocks.StructBlock', [[('table_id', 5), ('show_controls', 6), ('per_page', 7), ('table', 12)]], {}), 14: ('wagtail.blocks.StreamBlock', [[('text', 0), ('data_table', 13)]], {'help_text': 'Inner content revealed when the section is opened.', 'min_num': 1}), 15: ('wagtail.blocks.StructBlock', [[('label', 4), ('body', 14)]], {}), 16: ('wagtail.blocks.CharBlock', (), {'default': 'Last updated', 'help_text': 'Label shown before the date (e.g. "All data last updated").', 'required': False}), 17: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional text after the date (e.g. "(no longer updating)").', 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('label', 16), ('suffix', 17)]], {}), 19: ('wagtail.blocks.CharBlock', (), {'help_text': 'Key matching a figure in the DashboardData JSON.', 'required': True}), 20: ('wagtail.blocks.CharBlock', (), {'help_text': 'Accessibility description (aria-label) for the chart.', 'required': True}), 21: ('wagtail.blocks.IntegerBlock', (), {'default': 500, 'help_text': 'Chart height in pixels.', 'required': True}), 22: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional visible caption below the chart (separate from alt text).', 'required': False}), 23: ('wagtail.blocks.URLBlock', (), {'help_text': 'Link to the viz script in this repo on GitHub.', 'required': False}), 24: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Show a link to download the underlying data file.', 'required': False}), 25: ('wagtail.blocks.StructBlock', [[('figure_id', 19), ('alt_text', 20), ('height', 21), ('caption', 22), ('script_github_url', 23), ('show_data_download', 24)]], {}), 26: ('wagtail.blocks.static_block.StaticBlock', (), {'admin_text': 'A static block that displays information about the sampling sites.', 'template': 'cms/pages/slu_wastewater/partials/method_and_site_info.html'}), 27: ('wagtail.blocks.static_block.StaticBlock', (), {'admin_text': 'A static block that displays the quantitative analysis plot and the plot filter options in a collapsible section.', 'template': 'cms/pages/slu_wastewater/partials/quantitative_analysis.html'})})),
            ],
            options={
                'verbose_name': 'SLU Wastewater Dashboard Subpage',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TopicsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('content', wagtail.fields.StreamField([('text', 0), ('alert', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h4', 'h5', 'bold', 'italic', 'link'], 'help_text': 'Alert body. Rich text only: headings H4–H5, bold, italic, and links.'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], 'help_text': 'Controls the visual style (colour) of the alert on the public site.'}), 3: ('wagtail.blocks.StructBlock', [[('message', 1), ('alert_type', 2)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='DashboardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_title', models.CharField(default='', help_text='Human-readable dashboard name for admin display.', max_length=255)),
                ('dashboard_slug', models.SlugField(help_text='Must match the dashboard page slug. One data upload per dashboard.', max_length=255, unique=True)),
                ('source_file', models.FileField(upload_to='dashboard_data/')),
                ('source_file_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('data_updated_at', models.DateField(blank=True, help_text='Date shown on the public dashboard as when the underlying data was last updated. Updates automatically to today when the source file is replaced; you can override manually (e.g. historic migration date).', null=True)),
                ('uploaded_by', models.CharField(blank=True, max_length=255)),
                ('latest_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='latest revision')),
                ('research_group', models.ForeignKey(blank=True, help_text='Optional admin setting to restrict access to this dashboard data upload to a specific research group.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auth.group')),
            ],
            options={
                'verbose_name': 'Dashboard data upload',
                'verbose_name_plural': 'Dashboard data uploads',
                'ordering': ['dashboard_slug'],
            },
        ),
        migrations.CreateModel(
            name='DrrDatasetPage',
            fields=[
                ('dashboardpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.dashboardpage')),
                ('organism', models.CharField(default='SARS-CoV-2', max_length=255)),
                ('cell_line', models.CharField(blank=True, max_length=255)),
                ('screen_type', models.CharField(blank=True, max_length=255)),
                ('upstream_accession', models.CharField(blank=True, max_length=64)),
                ('upstream_bia_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'DRR Dataset Page',
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'cms.dashboardpage'),
        ),
        migrations.CreateModel(
            name='LiverResourceDashboardPage',
            fields=[
                ('dashboardpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.dashboardpage')),
            ],
            options={
                'verbose_name': 'Liver Resource Dashboard',
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'cms.dashboardpage'),
        ),
        migrations.CreateModel(
            name='SLUDashboardPage',
            fields=[
                ('dashboardpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.dashboardpage')),
                ('notice', wagtail.fields.RichTextField(blank=True)),
                ('notice_type', models.CharField(blank=True, choices=[('info', 'Info'), ('warning', 'Warning'), ('success', 'Success'), ('error', 'Error')], default='info', max_length=20)),
                ('slu_content', wagtail.fields.StreamField([('text', 0), ('alert', 3), ('collapsible', 15), ('last_updated', 18), ('plotly_figure', 25), ('recent_data_info', 26), ('overview_quantitative_plot', 27)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h4', 'h5', 'bold', 'italic', 'link'], 'help_text': 'Alert body. Rich text only: headings H4–H5, bold, italic, and links.'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], 'help_text': 'Controls the visual style (colour) of the alert on the public site.'}), 3: ('wagtail.blocks.StructBlock', [[('message', 1), ('alert_type', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Title shown in the always-visible summary line.', 'max_length': 255, 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Unique identifier for this table on the page (letters, numbers, hyphens). Defaults to a slugified version of the table caption.', 'max_length': 60, 'required': False, 'validators': [django.core.validators.RegexValidator('^[a-zA-Z0-9-]*$', 'Only letters, numbers, and hyphens.')]}), 6: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Show search, pagination, and per-page controls.', 'required': False}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('10', '10'), ('25', '25'), ('50', '50')], 'help_text': 'Number of rows per page when controls are visible (display all entries if controls are not shown).', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {}), 9: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 10: ('wagtail.blocks.FloatBlock', (), {}), 11: ('wagtail.blocks.IntegerBlock', (), {}), 12: ('wagtail.contrib.typed_table_block.blocks.TypedTableBlock', [[('text', 8), ('rich_text', 9), ('numeric', 10), ('integer', 11)]], {}), 13: ('wagtail.blocks.StructBlock', [[('table_id', 5), ('show_controls', 6), ('per_page', 7), ('table', 12)]], {}), 14: ('wagtail.blocks.StreamBlock', [[('text', 0), ('data_table', 13)]], {'help_text': 'Inner content revealed when the section is opened.', 'min_num': 1}), 15: ('wagtail.blocks.StructBlock', [[('label', 4), ('body', 14)]], {}), 16: ('wagtail.blocks.CharBlock', (), {'default': 'Last updated', 'help_text': 'Label shown before the date (e.g. "All data last updated").', 'required': False}), 17: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional text after the date (e.g. "(no longer updating)").', 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('label', 16), ('suffix', 17)]], {}), 19: ('wagtail.blocks.CharBlock', (), {'help_text': 'Key matching a figure in the DashboardData JSON.', 'required': True}), 20: ('wagtail.blocks.CharBlock', (), {'help_text': 'Accessibility description (aria-label) for the chart.', 'required': True}), 21: ('wagtail.blocks.IntegerBlock', (), {'default': 500, 'help_text': 'Chart height in pixels.', 'required': True}), 22: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional visible caption below the chart (separate from alt text).', 'required': False}), 23: ('wagtail.blocks.URLBlock', (), {'help_text': 'Link to the viz script in this repo on GitHub.', 'required': False}), 24: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Show a link to download the underlying data file.', 'required': False}), 25: ('wagtail.blocks.StructBlock', [[('figure_id', 19), ('alt_text', 20), ('height', 21), ('caption', 22), ('script_github_url', 23), ('show_data_download', 24)]], {}), 26: ('wagtail.blocks.static_block.StaticBlock', (), {'admin_text': 'A static block that displays a summary of the most recent data in the dataset as a collapsible section.', 'template': 'cms/pages/slu_wastewater/partials/recent_data_info.html'}), 27: ('wagtail.blocks.static_block.StaticBlock', (), {'admin_text': 'A static block that displays the quantitative overview plot and the plot filter options in a collapsible section.', 'template': 'cms/pages/slu_wastewater/partials/overview_quant_plot.html'})})),
            ],
            options={
                'verbose_name': 'SLU Wastewater Dashboard',
            },
            bases=('cms.dashboardpage',),
        ),
        migrations.CreateModel(
            name='DashboardEbiPathogen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('ebi_type_of_pathogen', models.CharField(max_length=255, verbose_name='Type of pathogen')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='ebi_type_of_pathogens', to='cms.dashboardpage')),
            ],
            options={
                'verbose_name': 'EBI type of pathogen',
                'verbose_name_plural': 'EBI types of pathogen',
            },
        ),
        migrations.CreateModel(
            name='DrrDatasetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_title', models.CharField(default='', max_length=255)),
                ('dataset_slug', models.SlugField(help_text='Must match the DrrDatasetPage slug. One data row per dataset.', max_length=255, unique=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('source_file_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('data_updated_at', models.DateField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('latest_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='latest revision')),
            ],
            options={
                'verbose_name': 'DRR dataset data',
                'verbose_name_plural': 'DRR dataset data',
                'ordering': ['dataset_slug'],
            },
        ),
        migrations.CreateModel(
            name='HighlightsAndEditorialsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('description', models.CharField(max_length=255)),
                ('image_caption', models.CharField(blank=True, max_length=255)),
                ('article_type', models.CharField(choices=[('data-highlight', 'Data Highlight'), ('editorial', 'Editorial')], max_length=50)),
                ('announcement', wagtail.fields.RichTextField(blank=True)),
                ('keywords', models.TextField(blank=True)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('content', wagtail.fields.StreamField([('text', 0), ('alert', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h4', 'h5', 'bold', 'italic', 'link'], 'help_text': 'Alert body. Rich text only: headings H4–H5, bold, italic, and links.'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], 'help_text': 'Controls the visual style (colour) of the alert on the public site.'}), 3: ('wagtail.blocks.StructBlock', [[('message', 1), ('alert_type', 2)]], {})})),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('hero_title', models.CharField(blank=True, help_text='The main title displayed in the hero section of the homepage.', max_length=255)),
                ('hero_text', models.CharField(blank=True, help_text='The text displayed below the main title in the hero section.', max_length=255)),
                ('hero_button_text', models.CharField(blank=True, help_text='The text displayed on the button in the hero section. A button can be added only if a hero title or text is added. This also cannot be empty if a hero button page or link is set.', max_length=70)),
                ('hero_button_link', models.URLField(blank=True, help_text='The URL that the button in the hero section links to.')),
                ('content', wagtail.fields.StreamField([('text', 0), ('alert', 3), ('collapsible', 15), ('page_section', 23)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h4', 'h5', 'bold', 'italic', 'link'], 'help_text': 'Alert body. Rich text only: headings H4–H5, bold, italic, and links.'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], 'help_text': 'Controls the visual style (colour) of the alert on the public site.'}), 3: ('wagtail.blocks.StructBlock', [[('message', 1), ('alert_type', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Title shown in the always-visible summary line.', 'max_length': 255, 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Unique identifier for this table on the page (letters, numbers, hyphens). Defaults to a slugified version of the table caption.', 'max_length': 60, 'required': False, 'validators': [django.core.validators.RegexValidator('^[a-zA-Z0-9-]*$', 'Only letters, numbers, and hyphens.')]}), 6: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Show search, pagination, and per-page controls.', 'required': False}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('10', '10'), ('25', '25'), ('50', '50')], 'help_text': 'Number of rows per page when controls are visible (display all entries if controls are not shown).', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {}), 9: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 10: ('wagtail.blocks.FloatBlock', (), {}), 11: ('wagtail.blocks.IntegerBlock', (), {}), 12: ('wagtail.contrib.typed_table_block.blocks.TypedTableBlock', [[('text', 8), ('rich_text', 9), ('numeric', 10), ('integer', 11)]], {}), 13: ('wagtail.blocks.StructBlock', [[('table_id', 5), ('show_controls', 6), ('per_page', 7), ('table', 12)]], {}), 14: ('wagtail.blocks.StreamBlock', [[('text', 0), ('data_table', 13)]], {'help_text': 'Inner content revealed when the section is opened.', 'min_num': 1}), 15: ('wagtail.blocks.StructBlock', [[('label', 4), ('body', 14)]], {}), 16: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Select a page to display its details.'}), 17: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional section title, if not given, the page title will be used.', 'max_length': 100, 'required': False}), 18: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Optional section description text.', 'required': False}), 19: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('title', 'Title (A-Z)'), ('created', 'Created date (newest first)'), ('updated', 'Updated date (newest first)'), ('data_updated', 'Data updated date (newest first)')], 'help_text': 'Sort child pages by title, first publish date, last publish date, or data updated date (for Dashboards).', 'label': 'Order by'}), 20: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Show a badge text on each child card.', 'required': False}), 21: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Show the date on each child card.', 'required': False}), 22: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Show the topics on each child card.', 'required': False}), 23: ('wagtail.blocks.StructBlock', [[('page', 16), ('title', 17), ('description', 18), ('order_by', 19), ('show_badge_in_child_pages', 20), ('show_date_in_child_pages', 21), ('show_topics_in_child_pages', 22)]], {})}, help_text='Content for the left column of the homepage.')),
                ('hero_button_page', models.ForeignKey(blank=True, help_text='The page that the button in the hero section links to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.WAGTAIL_PAGE_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NavigationMainMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=50)),
                ('has_submenu', models.BooleanField(blank=True, default=False)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.WAGTAIL_PAGE_MODEL)),
                ('parent', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_menu_items', to='cms.navigationmenu')),
            ],
            options={
                'verbose_name': 'Menu item',
                'verbose_name_plural': 'Menu items',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='NavigationSubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=50)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.WAGTAIL_PAGE_MODEL)),
                ('parent_menu', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_menu_items', to='cms.navigationmainmenu')),
            ],
            options={
                'verbose_name': 'Sub menu item',
                'verbose_name_plural': 'Sub menu items',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='NewsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('description', models.CharField(max_length=255)),
                ('content', wagtail.fields.StreamField([('text', 0), ('alert', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h4', 'h5', 'bold', 'italic', 'link'], 'help_text': 'Alert body. Rich text only: headings H4–H5, bold, italic, and links.'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], 'help_text': 'Controls the visual style (colour) of the alert on the public site.'}), 3: ('wagtail.blocks.StructBlock', [[('message', 1), ('alert_type', 2)]], {})})),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='OutbreakPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('historical', 'Historical')], default='ongoing', max_length=50)),
                ('content', wagtail.fields.StreamField([('text', 0), ('alert', 3), ('data_table', 12)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h4', 'h5', 'bold', 'italic', 'link'], 'help_text': 'Alert body. Rich text only: headings H4–H5, bold, italic, and links.'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], 'help_text': 'Controls the visual style (colour) of the alert on the public site.'}), 3: ('wagtail.blocks.StructBlock', [[('message', 1), ('alert_type', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Unique identifier for this table on the page (letters, numbers, hyphens). Defaults to a slugified version of the table caption.', 'max_length': 60, 'required': False, 'validators': [django.core.validators.RegexValidator('^[a-zA-Z0-9-]*$', 'Only letters, numbers, and hyphens.')]}), 5: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Show search, pagination, and per-page controls.', 'required': False}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('10', '10'), ('25', '25'), ('50', '50')], 'help_text': 'Number of rows per page when controls are visible (display all entries if controls are not shown).', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {}), 8: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 9: ('wagtail.blocks.FloatBlock', (), {}), 10: ('wagtail.blocks.IntegerBlock', (), {}), 11: ('wagtail.contrib.typed_table_block.blocks.TypedTableBlock', [[('text', 7), ('rich_text', 8), ('numeric', 9), ('integer', 10)]], {}), 12: ('wagtail.blocks.StructBlock', [[('table_id', 4), ('show_controls', 5), ('per_page', 6), ('table', 11)]], {})})),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PlpProjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('content', wagtail.fields.StreamField([('text', 0), ('alert', 3), ('data_table', 12), ('card', 17), ('card_grid', 19)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h4', 'h5', 'bold', 'italic', 'link'], 'help_text': 'Alert body. Rich text only: headings H4–H5, bold, italic, and links.'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], 'help_text': 'Controls the visual style (colour) of the alert on the public site.'}), 3: ('wagtail.blocks.StructBlock', [[('message', 1), ('alert_type', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Unique identifier for this table on the page (letters, numbers, hyphens). Defaults to a slugified version of the table caption.', 'max_length': 60, 'required': False, 'validators': [django.core.validators.RegexValidator('^[a-zA-Z0-9-]*$', 'Only letters, numbers, and hyphens.')]}), 5: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Show search, pagination, and per-page controls.', 'required': False}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('10', '10'), ('25', '25'), ('50', '50')], 'help_text': 'Number of rows per page when controls are visible (display all entries if controls are not shown).', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {}), 8: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 9: ('wagtail.blocks.FloatBlock', (), {}), 10: ('wagtail.blocks.IntegerBlock', (), {}), 11: ('wagtail.contrib.typed_table_block.blocks.TypedTableBlock', [[('text', 7), ('rich_text', 8), ('numeric', 9), ('integer', 10)]], {}), 12: ('wagtail.blocks.StructBlock', [[('table_id', 4), ('show_controls', 5), ('per_page', 6), ('table', 11)]], {}), 13: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Image shown at the top of the card (required).', 'required': True}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'Card heading (max 120 characters).', 'max_length': 120, 'required': True}), 15: ('wagtail.blocks.TextBlock', (), {'help_text': 'Short supporting text under the title (max 300 characters).', 'max_length': 300, 'required': True}), 16: ('wagtail.blocks.URLBlock', (), {'help_text': 'Full URL (https://…). Opens in a new browser tab.', 'required': True}), 17: ('wagtail.blocks.StructBlock', [[('image', 13), ('title', 14), ('description', 15), ('url', 16)]], {}), 18: ('wagtail.blocks.ListBlock', (17,), {'collapsed': True, 'help_text': 'Add at least one card. Each card links to an external URL.', 'label': 'Cards', 'min_num': 1}), 19: ('wagtail.blocks.StructBlock', [[('cards', 18)]], {})})),
                ('category', models.ForeignKey(blank=True, help_text='Required for top-level projects only; leave blank for subprojects.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='cms.plpcategory')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'PLP project page',
                'verbose_name_plural': 'PLP project pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TopicPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('description', models.CharField(max_length=255)),
                ('content', wagtail.fields.StreamField([('text', 0), ('alert', 3)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h4', 'h5', 'bold', 'italic', 'link'], 'help_text': 'Alert body. Rich text only: headings H4–H5, bold, italic, and links.'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], 'help_text': 'Controls the visual style (colour) of the alert on the public site.'}), 3: ('wagtail.blocks.StructBlock', [[('message', 1), ('alert_type', 2)]], {})})),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HighlightsAndEditorialsTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_topics', to='cms.highlightsandeditorialspage')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.topicpage')),
            ],
            options={
                'verbose_name': 'Related Topic',
                'verbose_name_plural': 'Related Topics',
            },
        ),
        migrations.CreateModel(
            name='DashboardTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_topics', to='cms.dashboardpage')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.topicpage')),
            ],
            options={
                'verbose_name': 'Related Topic',
                'verbose_name_plural': 'Related Topics',
            },
        ),
    ]
