# Generated by Django 6.0.5 on 2026-07-20 18:09

import django.core.validators
import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.routable_page.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('show_toc', models.BooleanField(blank=True, default=False, verbose_name='Show TOC')),
                ('content', wagtail.fields.StreamField([('text', 0), ('alert', 3), ('data_table', 12), ('collapsible', 16)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Main body copy. Use headings for structure; images optional.', 'verbose_name': 'Text (rich)'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h4', 'h5', 'bold', 'italic', 'link'], 'help_text': 'Alert body. Rich text only: headings H4–H5, bold, italic, and links.'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], 'help_text': 'Controls the visual style (colour) of the alert on the public site.'}), 3: ('wagtail.blocks.StructBlock', [[('message', 1), ('alert_type', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Unique identifier for this table on the page (letters, numbers, hyphens). Defaults to a slugified version of the table caption.', 'max_length': 60, 'required': False, 'validators': [django.core.validators.RegexValidator('^[a-zA-Z0-9-]*$', 'Only letters, numbers, and hyphens.')]}), 5: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Show search, pagination, and per-page controls.', 'required': False}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('10', '10'), ('25', '25'), ('50', '50')], 'help_text': 'Number of rows per page when controls are visible (display all entries if controls are not shown).', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {}), 8: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 9: ('wagtail.blocks.FloatBlock', (), {}), 10: ('wagtail.blocks.IntegerBlock', (), {}), 11: ('wagtail.contrib.typed_table_block.blocks.TypedTableBlock', [[('text', 7), ('rich_text', 8), ('numeric', 9), ('integer', 10)]], {}), 12: ('wagtail.blocks.StructBlock', [[('table_id', 4), ('show_controls', 5), ('per_page', 6), ('table', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'Title shown in the always-visible summary line.', 'max_length': 255, 'required': True}), 14: ('wagtail.blocks.RichTextBlock', (), {}), 15: ('wagtail.blocks.StreamBlock', [[('text', 14), ('data_table', 12)]], {'help_text': 'Inner content revealed when the section is opened.', 'min_num': 1}), 16: ('wagtail.blocks.StructBlock', [[('label', 13), ('body', 15)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CataloguePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('filter_label', models.CharField(max_length=100)),
                ('content', wagtail.fields.StreamField([('text', 0), ('alert', 3), ('card_grid', 12)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Rich text content. Supports headings, links, etc. for formatting.', 'verbose_name': 'Text (rich)'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h4', 'h5', 'bold', 'italic', 'link'], 'help_text': 'Alert body. Rich text only: headings H4–H5, bold, italic, and links.'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], 'help_text': 'Controls the visual style (colour) of the alert on the public site.'}), 3: ('wagtail.blocks.StructBlock', [[('message', 1), ('alert_type', 2)]], {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Image shown at the top of the card (required).', 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Card heading (max 120 characters).', 'max_length': 120, 'required': True}), 6: ('wagtail.blocks.TextBlock', (), {'help_text': 'Short supporting text under the title (max 300 characters).', 'max_length': 300, 'required': True}), 7: ('wagtail.blocks.URLBlock', (), {'help_text': 'Full URL (https://…). Opens in a new browser tab.', 'required': True}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Comma-separated types, used in filtering and labeling (Max 120 characters).', 'max_length': 120, 'required': True}), 9: ('wagtail.blocks.TextBlock', (), {'help_text': 'Optional comma-separated keywords for filtering (Max 300 characters).', 'max_length': 300, 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('image', 4), ('title', 5), ('description', 6), ('url', 7), ('type', 8), ('keywords', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {'collapsed': True, 'help_text': 'Add at least one card. Each card links to an external URL and includes catalogue type and keywords for filtering.', 'label': 'Catalogue cards', 'min_num': 1}), 12: ('wagtail.blocks.StructBlock', [[('cards', 11)]], {'help_text': 'Catalogue items added here will be displayed in a grid layout. The items are rendered as cards and ordered alphabetically.'})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='DashboardIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('content', wagtail.fields.StreamField([('text', 0), ('alert', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h4', 'h5', 'bold', 'italic', 'link'], 'help_text': 'Alert body. Rich text only: headings H4–H5, bold, italic, and links.'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], 'help_text': 'Controls the visual style (colour) of the alert on the public site.'}), 3: ('wagtail.blocks.StructBlock', [[('message', 1), ('alert_type', 2)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='DashboardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('show_toc', models.BooleanField(blank=True, default=False, verbose_name='Show TOC')),
                ('description', models.CharField(max_length=255)),
                ('data_status', models.CharField(choices=[('active', 'Active'), ('historic', 'Historic')], max_length=50)),
                ('keywords', models.TextField(blank=True)),
                ('content', wagtail.fields.StreamField([('text', 0), ('alert', 3), ('last_updated', 6), ('plotly_figure', 13), ('static_figure', 18)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h4', 'h5', 'bold', 'italic', 'link'], 'help_text': 'Alert body. Rich text only: headings H4–H5, bold, italic, and links.'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], 'help_text': 'Controls the visual style (colour) of the alert on the public site.'}), 3: ('wagtail.blocks.StructBlock', [[('message', 1), ('alert_type', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'Last updated', 'help_text': 'Label shown before the date (e.g. "All data last updated").', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional text after the date (e.g. "(no longer updating)").', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('label', 4), ('suffix', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Key matching a figure in the DashboardData JSON.', 'required': True}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Accessibility description (aria-label) for the chart.', 'required': True}), 9: ('wagtail.blocks.IntegerBlock', (), {'default': 500, 'help_text': 'Chart height in pixels.', 'required': True}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional visible caption below the chart (separate from alt text).', 'required': False}), 11: ('wagtail.blocks.URLBlock', (), {'help_text': 'Link to the viz script in this repo on GitHub.', 'required': False}), 12: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Show a link to download the underlying data file.', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('figure_id', 7), ('alt_text', 8), ('height', 9), ('caption', 10), ('script_github_url', 11), ('show_data_download', 12)]], {}), 14: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Upload an image, or leave empty and provide an external URL below.', 'required': False}), 15: ('wagtail.blocks.URLBlock', (), {'help_text': 'External image URL (e.g., Github, blobserver SVG). Used when no image is uploaded.', 'required': False}), 16: ('wagtail.blocks.CharBlock', (), {'help_text': 'Accessibility description (alt attribute) for the image.', 'required': True}), 17: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional visible caption below the figure (separate from alt text).', 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('image', 14), ('image_url', 15), ('alt_text', 16), ('caption', 17)]], {})})),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HighlightsAndEditorialsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('content', wagtail.fields.StreamField([('text', 0), ('alert', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h4', 'h5', 'bold', 'italic', 'link'], 'help_text': 'Alert body. Rich text only: headings H4–H5, bold, italic, and links.'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], 'help_text': 'Controls the visual style (colour) of the alert on the public site.'}), 3: ('wagtail.blocks.StructBlock', [[('message', 1), ('alert_type', 2)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NavigationMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Navigation menu',
                'verbose_name_plural': 'Navigation menu',
            },
        ),
        migrations.CreateModel(
            name='NewsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('content', wagtail.fields.StreamField([('text', 0), ('alert', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h4', 'h5', 'bold', 'italic', 'link'], 'help_text': 'Alert body. Rich text only: headings H4–H5, bold, italic, and links.'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], 'help_text': 'Controls the visual style (colour) of the alert on the public site.'}), 3: ('wagtail.blocks.StructBlock', [[('message', 1), ('alert_type', 2)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='OutbreaksIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('content', wagtail.fields.StreamField([('text', 0), ('alert', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h4', 'h5', 'bold', 'italic', 'link'], 'help_text': 'Alert body. Rich text only: headings H4–H5, bold, italic, and links.'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], 'help_text': 'Controls the visual style (colour) of the alert on the public site.'}), 3: ('wagtail.blocks.StructBlock', [[('message', 1), ('alert_type', 2)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PlpCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('group_label', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'PLP category',
                'verbose_name_plural': 'PLP categories',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PlpIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('content', wagtail.fields.StreamField([('text', 0), ('alert', 3), ('collapsible', 15)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h4', 'h5', 'bold', 'italic', 'link'], 'help_text': 'Alert body. Rich text only: headings H4–H5, bold, italic, and links.'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], 'help_text': 'Controls the visual style (colour) of the alert on the public site.'}), 3: ('wagtail.blocks.StructBlock', [[('message', 1), ('alert_type', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Title shown in the always-visible summary line.', 'max_length': 255, 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Unique identifier for this table on the page (letters, numbers, hyphens). Defaults to a slugified version of the table caption.', 'max_length': 60, 'required': False, 'validators': [django.core.validators.RegexValidator('^[a-zA-Z0-9-]*$', 'Only letters, numbers, and hyphens.')]}), 6: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Show search, pagination, and per-page controls.', 'required': False}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('10', '10'), ('25', '25'), ('50', '50')], 'help_text': 'Number of rows per page when controls are visible (display all entries if controls are not shown).', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {}), 9: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 10: ('wagtail.blocks.FloatBlock', (), {}), 11: ('wagtail.blocks.IntegerBlock', (), {}), 12: ('wagtail.contrib.typed_table_block.blocks.TypedTableBlock', [[('text', 8), ('rich_text', 9), ('numeric', 10), ('integer', 11)]], {}), 13: ('wagtail.blocks.StructBlock', [[('table_id', 5), ('show_controls', 6), ('per_page', 7), ('table', 12)]], {}), 14: ('wagtail.blocks.StreamBlock', [[('text', 0), ('data_table', 13)]], {'help_text': 'Inner content revealed when the section is opened.', 'min_num': 1}), 15: ('wagtail.blocks.StructBlock', [[('label', 4), ('body', 14)]], {})})),
            ],
            options={
                'verbose_name': 'PLP program page',
                'verbose_name_plural': 'PLP program pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PortalDataPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('datatype', models.CharField(choices=[('metabolomics', 'Metabolomics')], default='metabolomics', max_length=64)),
                ('default_page_size', models.PositiveIntegerField(default=25)),
                ('content', wagtail.fields.StreamField([('text', 0), ('alert', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h4', 'h5', 'bold', 'italic', 'link'], 'help_text': 'Alert body. Rich text only: headings H4–H5, bold, italic, and links.'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], 'help_text': 'Controls the visual style (colour) of the alert on the public site.'}), 3: ('wagtail.blocks.StructBlock', [[('message', 1), ('alert_type', 2)]], {})})),
            ],
            options={
                'verbose_name': 'Portal data page',
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='SiteAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', wagtail.fields.RichTextField()),
                ('announcement_type', models.CharField(choices=[('maintenance', 'Maintenance'), ('survey', 'Survey')], max_length=20)),
                ('is_enabled', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(blank=True, db_index=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'Site announcement',
                'verbose_name_plural': 'Site announcements',
                'ordering': ['sort_order', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='TopicsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('content', wagtail.fields.StreamField([('text', 0), ('alert', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h4', 'h5', 'bold', 'italic', 'link'], 'help_text': 'Alert body. Rich text only: headings H4–H5, bold, italic, and links.'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], 'help_text': 'Controls the visual style (colour) of the alert on the public site.'}), 3: ('wagtail.blocks.StructBlock', [[('message', 1), ('alert_type', 2)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='DashboardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_title', models.CharField(default='', help_text='Human-readable dashboard name for admin display.', max_length=255)),
                ('dashboard_slug', models.SlugField(help_text='Must match the dashboard page slug. One data upload per dashboard.', max_length=255, unique=True)),
                ('source_file', models.FileField(upload_to='dashboard_data/')),
                ('source_file_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('data_updated_at', models.DateField(blank=True, help_text='Date shown on the public dashboard as when the underlying data was last updated. Updates automatically to today when the source file is replaced; you can override manually (e.g. historic migration date).', null=True)),
                ('uploaded_by', models.CharField(blank=True, max_length=255)),
                ('latest_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='latest revision')),
            ],
            options={
                'verbose_name': 'Dashboard data upload',
                'verbose_name_plural': 'Dashboard data uploads',
                'ordering': ['dashboard_slug'],
            },
        ),
        migrations.CreateModel(
            name='LiverResourceDashboardPage',
            fields=[
                ('dashboardpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.dashboardpage')),
            ],
            options={
                'verbose_name': 'Liver Resource Dashboard',
            },
            bases=('cms.dashboardpage',),
        ),
        migrations.CreateModel(
            name='HighlightsAndEditorialsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', models.CharField(max_length=255)),
                ('image_caption', models.CharField(blank=True, max_length=255)),
                ('article_type', models.CharField(choices=[('data-highlight', 'Data Highlight'), ('editorial', 'Editorial')], max_length=50)),
                ('announcement', wagtail.fields.RichTextField(blank=True)),
                ('keywords', models.TextField(blank=True)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('content', wagtail.fields.StreamField([('text', 0), ('alert', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h4', 'h5', 'bold', 'italic', 'link'], 'help_text': 'Alert body. Rich text only: headings H4–H5, bold, italic, and links.'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], 'help_text': 'Controls the visual style (colour) of the alert on the public site.'}), 3: ('wagtail.blocks.StructBlock', [[('message', 1), ('alert_type', 2)]], {})})),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NavigationMainMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=50)),
                ('has_submenu', models.BooleanField(blank=True, default=False)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('parent', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_menu_items', to='cms.navigationmenu')),
            ],
            options={
                'verbose_name': 'Menu item',
                'verbose_name_plural': 'Menu items',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='NavigationSubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=50)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('parent_menu', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_menu_items', to='cms.navigationmainmenu')),
            ],
            options={
                'verbose_name': 'Sub menu item',
                'verbose_name_plural': 'Sub menu items',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='NewsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', models.CharField(max_length=255)),
                ('content', wagtail.fields.StreamField([('text', 0), ('alert', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h4', 'h5', 'bold', 'italic', 'link'], 'help_text': 'Alert body. Rich text only: headings H4–H5, bold, italic, and links.'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], 'help_text': 'Controls the visual style (colour) of the alert on the public site.'}), 3: ('wagtail.blocks.StructBlock', [[('message', 1), ('alert_type', 2)]], {})})),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='OutbreakPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('historical', 'Historical')], default='ongoing', max_length=50)),
                ('content', wagtail.fields.StreamField([('text', 0), ('alert', 3), ('data_table', 12)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h4', 'h5', 'bold', 'italic', 'link'], 'help_text': 'Alert body. Rich text only: headings H4–H5, bold, italic, and links.'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], 'help_text': 'Controls the visual style (colour) of the alert on the public site.'}), 3: ('wagtail.blocks.StructBlock', [[('message', 1), ('alert_type', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Unique identifier for this table on the page (letters, numbers, hyphens). Defaults to a slugified version of the table caption.', 'max_length': 60, 'required': False, 'validators': [django.core.validators.RegexValidator('^[a-zA-Z0-9-]*$', 'Only letters, numbers, and hyphens.')]}), 5: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Show search, pagination, and per-page controls.', 'required': False}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('10', '10'), ('25', '25'), ('50', '50')], 'help_text': 'Number of rows per page when controls are visible (display all entries if controls are not shown).', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {}), 8: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 9: ('wagtail.blocks.FloatBlock', (), {}), 10: ('wagtail.blocks.IntegerBlock', (), {}), 11: ('wagtail.contrib.typed_table_block.blocks.TypedTableBlock', [[('text', 7), ('rich_text', 8), ('numeric', 9), ('integer', 10)]], {}), 12: ('wagtail.blocks.StructBlock', [[('table_id', 4), ('show_controls', 5), ('per_page', 6), ('table', 11)]], {})})),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PlpProjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('content', wagtail.fields.StreamField([('text', 0), ('alert', 3), ('data_table', 12), ('card', 17), ('card_grid', 19)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h4', 'h5', 'bold', 'italic', 'link'], 'help_text': 'Alert body. Rich text only: headings H4–H5, bold, italic, and links.'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], 'help_text': 'Controls the visual style (colour) of the alert on the public site.'}), 3: ('wagtail.blocks.StructBlock', [[('message', 1), ('alert_type', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Unique identifier for this table on the page (letters, numbers, hyphens). Defaults to a slugified version of the table caption.', 'max_length': 60, 'required': False, 'validators': [django.core.validators.RegexValidator('^[a-zA-Z0-9-]*$', 'Only letters, numbers, and hyphens.')]}), 5: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Show search, pagination, and per-page controls.', 'required': False}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('10', '10'), ('25', '25'), ('50', '50')], 'help_text': 'Number of rows per page when controls are visible (display all entries if controls are not shown).', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {}), 8: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 9: ('wagtail.blocks.FloatBlock', (), {}), 10: ('wagtail.blocks.IntegerBlock', (), {}), 11: ('wagtail.contrib.typed_table_block.blocks.TypedTableBlock', [[('text', 7), ('rich_text', 8), ('numeric', 9), ('integer', 10)]], {}), 12: ('wagtail.blocks.StructBlock', [[('table_id', 4), ('show_controls', 5), ('per_page', 6), ('table', 11)]], {}), 13: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Image shown at the top of the card (required).', 'required': True}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'Card heading (max 120 characters).', 'max_length': 120, 'required': True}), 15: ('wagtail.blocks.TextBlock', (), {'help_text': 'Short supporting text under the title (max 300 characters).', 'max_length': 300, 'required': True}), 16: ('wagtail.blocks.URLBlock', (), {'help_text': 'Full URL (https://…). Opens in a new browser tab.', 'required': True}), 17: ('wagtail.blocks.StructBlock', [[('image', 13), ('title', 14), ('description', 15), ('url', 16)]], {}), 18: ('wagtail.blocks.ListBlock', (17,), {'collapsed': True, 'help_text': 'Add at least one card. Each card links to an external URL.', 'label': 'Cards', 'min_num': 1}), 19: ('wagtail.blocks.StructBlock', [[('cards', 18)]], {})})),
                ('category', models.ForeignKey(blank=True, help_text='Required for top-level projects only; leave blank for subprojects.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='cms.plpcategory')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'PLP project page',
                'verbose_name_plural': 'PLP project pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TopicPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', models.CharField(max_length=255)),
                ('content', wagtail.fields.StreamField([('text', 0), ('alert', 3)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h4', 'h5', 'bold', 'italic', 'link'], 'help_text': 'Alert body. Rich text only: headings H4–H5, bold, italic, and links.'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], 'help_text': 'Controls the visual style (colour) of the alert on the public site.'}), 3: ('wagtail.blocks.StructBlock', [[('message', 1), ('alert_type', 2)]], {})})),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HighlightsAndEditorialsTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_topics', to='cms.highlightsandeditorialspage')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.topicpage')),
            ],
            options={
                'verbose_name': 'Related Topic',
                'verbose_name_plural': 'Related Topics',
            },
        ),
        migrations.CreateModel(
            name='DashboardTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_topics', to='cms.dashboardpage')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.topicpage')),
            ],
            options={
                'verbose_name': 'Related Topic',
                'verbose_name_plural': 'Related Topics',
            },
        ),
    ]
