# Generated by Django 6.1 on 2026-09-07 12:58

import django.core.validators
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicpage',
            name='content',
            field=wagtail.fields.StreamField([('text', 0), ('alert', 3), ('data_table', 12), ('card_grid', 19), ('collapsible', 23), ('matomo_opt_out', 24)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Main body copy. Use headings for structure; images optional.', 'verbose_name': 'Text (rich)'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h4', 'h5', 'bold', 'italic', 'link'], 'help_text': 'Alert body. Rich text only: headings H4–H5, bold, italic, and links.'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], 'help_text': 'Controls the visual style (colour) of the alert on the public site.'}), 3: ('wagtail.blocks.StructBlock', [[('message', 1), ('alert_type', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Unique identifier for this table on the page (letters, numbers, hyphens). Defaults to a slugified version of the table caption.', 'max_length': 60, 'required': False, 'validators': [django.core.validators.RegexValidator('^[a-zA-Z0-9-]*$', 'Only letters, numbers, and hyphens.')]}), 5: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Show search, pagination, and per-page controls.', 'required': False}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('10', '10'), ('25', '25'), ('50', '50')], 'help_text': 'Number of rows per page when controls are visible (display all entries if controls are not shown).', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {}), 8: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 9: ('wagtail.blocks.FloatBlock', (), {}), 10: ('wagtail.blocks.IntegerBlock', (), {}), 11: ('wagtail.contrib.typed_table_block.blocks.TypedTableBlock', [[('text', 7), ('rich_text', 8), ('numeric', 9), ('integer', 10)]], {}), 12: ('wagtail.blocks.StructBlock', [[('table_id', 4), ('show_controls', 5), ('per_page', 6), ('table', 11)]], {}), 13: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Image shown at the top of the card (required).', 'required': True}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'Card heading (max 120 characters).', 'max_length': 120, 'required': True}), 15: ('wagtail.blocks.TextBlock', (), {'help_text': 'Short supporting text under the title (max 300 characters).', 'max_length': 300, 'required': True}), 16: ('wagtail.blocks.URLBlock', (), {'help_text': 'Full URL (https://…). Opens in a new browser tab.', 'required': True}), 17: ('wagtail.blocks.StructBlock', [[('image', 13), ('title', 14), ('description', 15), ('url', 16)]], {}), 18: ('wagtail.blocks.ListBlock', (17,), {'collapsed': True, 'help_text': 'Add at least one card. Each card links to an external URL.', 'label': 'Cards', 'min_num': 1}), 19: ('wagtail.blocks.StructBlock', [[('cards', 18)]], {}), 20: ('wagtail.blocks.CharBlock', (), {'help_text': 'Title shown in the always-visible summary line.', 'max_length': 255, 'required': True}), 21: ('wagtail.blocks.RichTextBlock', (), {}), 22: ('wagtail.blocks.StreamBlock', [[('text', 21), ('data_table', 12)]], {'help_text': 'Inner content revealed when the section is opened.', 'min_num': 1}), 23: ('wagtail.blocks.StructBlock', [[('label', 20), ('body', 22)]], {}), 24: ('wagtail.blocks.static_block.StaticBlock', (), {'admin_text': 'Displays the Matomo analytics opt-out widget.', 'template': 'cms/components/matomo_opt_out.html'})}),
        ),
    ]
