# Generated by Django 6.1 on 2026-09-03 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cms', '0001_initial'),
        ('wagtailcore', '0098_apitoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorsApprovalTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.task')),
                ('groups', models.ManyToManyField(help_text='Pages/snippets at this step in a workflow will be moderated or approved by these groups of users', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'Editors Approval Task',
                'verbose_name_plural': 'Editors Approval Tasks',
            },
            bases=('wagtailcore.task',),
        ),
    ]
