# Generated by Django 6.1.1 on 2026-09-29 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_existing_image_disclosures(apps, schema_editor):
    """Create one unconfirmed disclosure row for every existing Wagtail image."""
    from cms.image_ai import backfill_image_disclosures

    backfill_image_disclosures(apps, schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_editorsapprovaltask'),
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAIDisclosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_status', models.CharField(choices=[('unreviewed', 'Unreviewed'), ('not_ai', 'Not AI-generated'), ('fully_ai', 'Fully AI-generated'), ('partially_ai', 'Partially AI-modified')], default='unreviewed', max_length=20)),
                ('picture_like', models.CharField(choices=[('unreviewed', 'Unreviewed'), ('yes', 'Yes'), ('no', 'No')], default='unreviewed', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('label_version', models.CharField(blank=True, max_length=64)),
                ('labelled_file_hash', models.CharField(blank=True, max_length=64)),
                ('labelled_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_disclosure', to='wagtailimages.image')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI image disclosure',
                'verbose_name_plural': 'AI image disclosures',
            },
        ),
        migrations.RunPython(seed_existing_image_disclosures, migrations.RunPython.noop),
    ]
