# Generated by Django 6.1.1 on 2026-10-01 13:11

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0005_editorsapprovaltask"),
    ]

    operations = [
        migrations.AlterField(
            model_name="availabledatapage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("text", 0),
                    ("alert", 3),
                    ("available_data", 4),
                    ("portal_data_summary", 10),
                ],
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {}),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["h4", "h5", "bold", "italic", "link"],
                            "help_text": "Alert body. Rich text only: headings H4–H5, bold, italic, and links.",
                        },
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("info", "Info"),
                                ("success", "Success"),
                                ("warning", "Warning"),
                                ("error", "Error"),
                            ],
                            "help_text": "Controls the visual style (colour) of the alert on the public site.",
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("message", 1), ("alert_type", 2)]],
                        {},
                    ),
                    4: (
                        "wagtail.blocks.static_block.StaticBlock",
                        (),
                        {
                            "admin_text": "Displays EBI dataset counts by category, loaded via HTMX. NOTE: This requires the page to be published until then, previewing it will show an error instead of the counts.",
                            "template": "cms/pages/available_data/partials/available_data_section.html",
                        },
                    ),
                    5: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "help_text": "The Portal data page to summarise and link to.",
                            "page_type": ["cms.PortalDataPage"],
                        },
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Section heading. Defaults to the data type (e.g. "Metabolomics").',
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("technology", "Technology"),
                                ("platforms", "Platforms"),
                                ("year", "Year"),
                                ("design_types", "Design types"),
                                ("factors", "Factors"),
                                ("repository", "Repository"),
                            ],
                            "help_text": "Which field to break the study counts down by.",
                        },
                    ),
                    8: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 8,
                            "help_text": "Maximum number of breakdown buttons to show.",
                            "max_value": 50,
                            "min_value": 1,
                        },
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Only count studies from this country (e.g. "Sweden"). Leave blank to include all studies.',
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("page", 5),
                                ("title", 6),
                                ("breakdown", 7),
                                ("max_rows", 8),
                                ("country", 9),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
