# Generated by Django 6.1.1 on 2026-10-01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0006_image_ai_disclosure"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imageaidisclosure",
            name="review_notes",
        ),
    ]
