# Generated by Django 6.1.1 on 2026-10-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_available_data_portal_data_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='image_caption',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
