"""Service functions for exporting item data for the Portal data page."""

from __future__ import annotations

import csv
import io
import json
from collections.abc import Iterable, Mapping

# Fields we include in exports:
# - key in the item dict
# - human-readable column header
EXPORT_FIELDS: list[tuple[str, str]] = [
    ("id", "Accession"),
    ("title", "Title"),
    ("pathogen", "Pathogen"),
    ("matrix", "Matrix"),
    ("instrument", "Instrument"),
    ("country", "Country"),
    ("year", "Year"),
    ("repository", "Repository"),
    ("repo_url", "Repository URL"),
]


def _normalize_items(items: Iterable[Mapping[str, object]]) -> list[dict]:
    """Normalize view items for export.

    Take whatever dicts the view passes in and return a list of clean dicts
    containing only the fields we want to export, with None -> "".
    """

    normalized: list[dict] = []

    for it in items:
        row: dict[str, object] = {}
        for key, _ in EXPORT_FIELDS:
            value = it.get(key, "")
            if value is None:
                value = ""
            row[key] = value
        normalized.append(row)

    return normalized


def build_export_tsv(
    items: Iterable[Mapping[str, object]],
    default_filename: str = "export.tsv",
) -> tuple[str, str, str]:
    """Build a TSV export from a sequence of item dicts.

    Returns: (content_str, filename, content_type)
    """

    rows = _normalize_items(items)

    buf = io.StringIO()
    writer = csv.writer(buf, delimiter="\t")

    # Header row
    writer.writerow([label for _, label in EXPORT_FIELDS])

    # Data rows
    for row in rows:
        writer.writerow([row.get(key, "") for key, _ in EXPORT_FIELDS])

    content = buf.getvalue()
    buf.close()

    filename = default_filename or "export.tsv"
    content_type = "text/tab-separated-values; charset=utf-8"
    return content, filename, content_type


def build_download_script(
    accessions: Iterable[str],
    default_filename: str = "metabolights_download.sh",
) -> tuple[str, str, str]:
    """Build a shell script that bulk-downloads the given MetaboLights studies.

    The script never sends any study data through our server: it shells out to
    MetaboLights' own 'mtbls' CLI (the metabolights-utils package), which pulls
    each study's public data directly from MetaboLights' FTP-backed storage.

    Returns: (content_str, filename, content_type)
    """
    lines = [
        "#!/usr/bin/env bash",
        "# Bulk download script generated by the Swedish Pathogens Portal.",
        "# Downloads the selected MetaboLights studies directly from MetaboLights -",
        "# no study data passes through the portal itself.",
        "#",
        "# Requires the MetaboLights command line tool (metabolights-utils):",
        "#   pip install metabolights-utils",
        "set -euo pipefail",
        "",
        "if ! command -v mtbls >/dev/null 2>&1; then",
        "    echo \"The 'mtbls' command was not found.\" >&2",
        '    echo "Install it first with: pip install metabolights-utils" >&2',
        '    echo "(requires Python 3.10+)" >&2',
        "    exit 1",
        "fi",
        "",
        "# 'mtbls' being on PATH does not mean it actually runs - a broken",
        "# install (outdated Python, a missing dependency, ...) can make the",
        "# command exist but crash. Surface the real error instead of letting",
        "# it happen partway through the downloads below.",
        "mtbls_version_output=$(mtbls --version 2>&1) || {",
        "    echo \"The 'mtbls' command was found but failed to run:\" >&2",
        '    echo "$mtbls_version_output" >&2',
        '    echo "" >&2',
        '    echo "metabolights-utils needs Python 3.10+ and all of its" >&2',
        '    echo "dependencies installed. Try reinstalling it in a fresh" >&2',
        '    echo "environment, e.g.:" >&2',
        '    echo "  conda create -n mtbls python=3.11 -y" >&2',
        '    echo "  conda activate mtbls" >&2',
        '    echo "  pip install --upgrade metabolights-utils requests" >&2',
        "    exit 1",
        "}",
        "",
        "# 'mtbls' ignores the shell's cwd by default and writes into its own",
        "# ~/metabolights_data cache unless told otherwise, so we point --local_path",
        "# at this folder explicitly below to keep everything in one predictable place.",
        "mkdir -p metabolights_downloads",
        "cd metabolights_downloads",
        "",
    ]
    for accession in accessions:
        lines.append(f'echo "Downloading {accession} ..."')
        lines.append(
            f'mtbls public download "{accession}" --local_path "$(pwd)" --override_local_files'
        )
    lines.append("")
    lines.append('echo "Done. Files are in $(pwd)"')
    content = "\n".join(lines) + "\n"

    filename = default_filename
    content_type = "text/x-shellscript; charset=utf-8"
    return content, filename, content_type


def build_export_json(
    items: Iterable[Mapping[str, object]],
    default_filename: str = "export.json",
) -> tuple[str, str, str]:
    """Build a JSON export from a sequence of item dicts.

    Returns: (content_str, filename, content_type)
    """

    rows = _normalize_items(items)
    content = json.dumps(rows, indent=2, ensure_ascii=False)

    filename = default_filename or "export.json"
    content_type = "application/json; charset=utf-8"
    return content, filename, content_type
