# Generated by Django 5.2.6 on 2025-09-26 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='published',
            new_name='isactive',
        ),
    ]
