# Pa11y: A tool to check accessibility issues on a webpage
#
# The config file used by this workflow is in the ".github"
# directory of the repository.
#
# The sitemap.xml is provided via live instance URL.
#
# This workflow is scheduled to run every Monday at 12:12 UTC,
# it can also be run manually from repo's GitHub action page.

---
name: Pa11y Accessibility Check

on:
  workflow_dispatch:
  # TODO: Uncomment the following lines to enable scheduled runs
  # schedule:
  #   - cron: '12 12 * * MON'

jobs:
  pa11y:
    name: Pa11y Check
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Set up Node.js 24
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: 24

      - name: Install Pa11y CI
        run: npm install -g pa11y-ci

      # TODO: Update sitemap URL to main site after hard launch
      - name: Run Pa11y CI
        run: |
          pa11y-ci \
            --config ${GITHUB_WORKSPACE}/.github/pa11y/pa11y.config \
            --sitemap https://swedish-pathogens-portal.scilifelab-2-dev.sys.kth.se/sitemap.xml

      - name: Generate Pa11y summary
        if: always()
        run: |
          if [[ -f pa11y-results.json ]]; then
            bash \
              "${GITHUB_WORKSPACE}/.github/pa11y/generate_summary.sh" \
              pa11y-results.json \
            >> "$GITHUB_STEP_SUMMARY"
          fi
