# Generated by Django 5.2.6 on 2025-09-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the topic', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly version of the name (auto-generated from name)', max_length=100, unique=True)),
                ('description', models.TextField(help_text='Description of the topic to display in the card')),
                ('content', models.TextField(help_text='Rich text content in markdown format (displayed on topic detail page)')),
                ('thumbnail_image', models.ImageField(help_text='Thumbnail image for the topic card display', upload_to='topics/images/')),
                ('alert_message', models.TextField(blank=True, help_text='Optional alert message to display prominently on the topic page', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this topic is active and visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ['name'],
            },
        ),
    ]
